"""FlashInfer-style inference primitives for Ascend NPU."""

from .runtime import (
    ArtifactFormat,
    ArtifactKind,
    ArtifactRef,
    ArtifactVerificationError,
    Backend,
    CFieldABI,
    CPrimitive,
    CStructABI,
    DeviceCapability,
    DispatchError,
    KernelConstraints,
    KernelCapabilityBinding,
    KernelArgumentABI,
    KernelArgumentDirection,
    KernelArgumentPassing,
    KernelBinaryABI,
    KernelDescriptor,
    KernelErrorABI,
    KernelErrorCodeABI,
    KernelLaunchABI,
    KernelRegistry,
    Plan,
    QuantSpec,
    SchemaError,
    WorkloadSpec,
    WorkspaceFormula,
    build_plan,
)
from .version import __version__
from .attention import BatchAttention
from .decode import (
    BatchDecodeWithPagedKVCacheWrapper,
    single_decode_with_kv_cache,
    single_decode_with_kv_cache_return_lse,
    single_decode_with_kv_cache_with_jit_module,
)
from .prefill import (
    BatchPrefillWithPagedKVCacheWrapper,
    BatchPrefillWithRaggedKVCacheWrapper,
    single_prefill_with_kv_cache,
    single_prefill_with_kv_cache_return_lse,
    single_prefill_with_kv_cache_with_jit_module,
)
from . import jit as jit

__all__ = [
    "ArtifactFormat",
    "ArtifactKind",
    "ArtifactRef",
    "ArtifactVerificationError",
    "Backend",
    "CFieldABI",
    "CPrimitive",
    "CStructABI",
    "BatchAttention",
    "BatchDecodeWithPagedKVCacheWrapper",
    "BatchPrefillWithPagedKVCacheWrapper",
    "BatchPrefillWithRaggedKVCacheWrapper",
    "DeviceCapability",
    "DispatchError",
    "KernelConstraints",
    "KernelCapabilityBinding",
    "KernelArgumentABI",
    "KernelArgumentDirection",
    "KernelArgumentPassing",
    "KernelBinaryABI",
    "KernelDescriptor",
    "KernelErrorABI",
    "KernelErrorCodeABI",
    "KernelLaunchABI",
    "KernelRegistry",
    "Plan",
    "QuantSpec",
    "SchemaError",
    "WorkloadSpec",
    "WorkspaceFormula",
    "__version__",
    "build_plan",
    "jit",
    "single_decode_with_kv_cache",
    "single_decode_with_kv_cache_return_lse",
    "single_decode_with_kv_cache_with_jit_module",
    "single_prefill_with_kv_cache",
    "single_prefill_with_kv_cache_return_lse",
    "single_prefill_with_kv_cache_with_jit_module",
]
